### PR TITLE
Improve file operations Messages readability

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
- Improve file operations Messages readability
  + add dedicated "type" field for [file copied], [file deleted]...
  + add new Title and Path fields for existing entries: SyncTaskName and full_path
- When we click a Sync Event entry in History, properly show these entries to the log:
  + msgs_mirror_confirm_move_cancel
  + msgs_mirror_confirm_copy_cancel
  + msgs_mirror_confirm_delete_cancel
- fix potential null StringBuilder if message is empty in addLogMsg()
- Translate and fix new entries
  + fix Time (HHMMSS) button label in english
  + translate new entries
  + small russian formatting
  + use more concise message labels for file operations
  + add missing entries in Excel template

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
I hope you like this one and merge it. I was really bothered by the readability of file operations in the Messages.
- if ok, I will add the colors directly to Utilities lib instead of the inline code: more proper
- I will also adapt showArchiveMsg() like showMsg for the remaining operations

Images below

**Comment by PhilZ-cwm6** [comment]
Screenshot_1591515986
Screenshot_1591516681
Screenshot_1591516425
Screenshot_1591516716
Screenshot_1591516476
Screenshot_1591516495
Screenshot_1591516503
Screenshot_1591516535
Screenshot_1591516546

**Comment by PhilZ-cwm6** [comment]
Light theme
Screenshot_1591516746
Screenshot_1591516764
Screenshot_1591516776
Screenshot_1591516790

**Comment by PhilZ-cwm6** [comment]
Black Theme
Screenshot_1591516853
Screenshot_1591516869

**Comment by PhilZ-cwm6** [comment]
Archive
Screenshot_1591517133

**Comment by PhilZ-cwm6** [comment]
I hope you like this one and merge it. I was really bothered by the readability of file operations in the Messages.
- if ok, I will add the colors directly to Utilities lib instead of the inline code: more proper
- I will also adapt showArchiveMsg() like showMsg for the remaining operations

Images below

**Comment by PhilZ-cwm6** [comment]
Image with a Before (the actual showArchiveMsg() still in code) and after:
Screenshot_1591517157


Current patch with the 3 themes: balck and Light at end

Screenshot_1591515986
Screenshot_1591516681
Screenshot_1591516425
Screenshot_1591516716
Screenshot_1591516476
Screenshot_1591516495
Screenshot_1591516503
Screenshot_1591516535
Screenshot_1591516546

**Comment by PhilZ-cwm6** [comment]
Light theme
Screenshot_1591516746
Screenshot_1591516764
Screenshot_1591516776
Screenshot_1591516790

**Comment by PhilZ-cwm6** [comment]
Black Theme
Screenshot_1591516853
Screenshot_1591516869

**Comment by PhilZ-cwm6** [comment]
Archive
Screenshot_1591517133

**Comment by PhilZ-cwm6** [comment]
Before and after the archive cleanup with previous 2 commits:
Screenshot_1591534491
Screenshot_1591537993

**Comment by PhilZ-cwm6** [comment]
And that was the last one:
Screenshot_1591539665

**Comment by PhilZ-cwm6** [comment]
I hope you like this one and merge it. I was really bothered by the readability of file operations in the Messages. It was in my timeline 2 months ago, but was at 50%. 
It was one of the aspects that pushed my away from the app on my first test months ago, when I was using FolderSync

- if ok, I will add the colors directly to Utilities lib instead of the inline code: more proper
~~- I will also adapt showArchiveMsg() like showMsg for the remaining operations~~: Added

Thank you and best regards

**Comment by PhilZ-cwm6** [comment]
**Before:**
Screenshot_1591534491

**Mix Before / After**
Screenshot_1591517157

**After:**
- Sync Start event in White font, Cyan on Theme Light
- Skipped: invalid chars, warning color
- Overwritten: warning color
- Cancelled, on user prompt: warning color
- Archive, copy and normal: in regular color
- Delete: in red

Screenshot_1591516425

Screenshot_1591516716

Screenshot_1591517133

Screenshot_1591516764

Screenshot_1591537993

Screenshot_1591516495

Screenshot_1591516776

**Comment by PhilZ-cwm6** [comment]
More images
Screenshot_1591516503
Screenshot_1591516790
Screenshot_1591539665
Screenshot_1591516535

Screenshot_1591516546

**Comment by PhilZ-cwm6** [comment]
Black Theme
Screenshot_1591516853

Screenshot_1591516869

**Comment by PhilZ-cwm6** [comment]
added a last fix to properly display Messages from old version after update

**Comment by Sentaroh** [comment]
Thank you for your improvement.

Merge your request.

I changed the way Message is displayed. What do you think?
（See Branch 2.30-modify-message-layout)
Before
図2
After
図1

図3

Best regards.

**Comment by PhilZ-cwm6** [comment]
Thank you for merging it
I like the new layout 
I will commit a small fix you forgot
Best regards

**Pull request closed without merging**
