### PR TITLE
English translation fixes + Fr translation

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
- Please look at the 2 highlighted fields with a note
- Can you push a beta branch with the fixed translations and french so that I can compile and test it before finalizing the translations ?

Note: the english was really bad and hard to understand :-)
Once the menus are fixed, I will look at the help files for eng fix + fr translation

Best regards

**Comment by PhilZ-cwm6** [comment]
edit: I followed the code as much as I could to do the translations, so I found many confusing menu dependencies that I am trying to fix partially by submitting the patches

**Comment by Sentaroh** [comment]
Thank you for your translation.

2.28-translation branch has been pushed.
See Sentaroh/Urilities/message_translation_utilties.xlsm for more information around the common Dialog.

Best regards.

**Comment by PhilZ-cwm6** [comment]
great, I will focus on finishing translation and eng fixes before looking at the other points

**Pull request closed without merging**
