### PR TITLE
remove duplicate

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**

### CODE REVIEW

**Comment by Sentaroh** [comment]
Hi,
getDSTSavings() can retrieve an Offset value regardless of the date and time if the time zone is set to DST.
https://developer.android.com/reference/java/util/TimeZone#getDSTSavings()

Given that the DST will be changed, I think it's better to use getDSTSavings() to get the Offset.

Best regards.

**Comment by Sentaroh** [comment]
Hi,

How about using getDSTSaving() to get the default value so that the user can change it?

Best regards.

**Comment by PhilZ-cwm6** [comment]
You are right about getDSTSaving. I also thought about a selection list: auto (GetDSTSaving()), 1 (always), 0 (never). Would give user choice to force it.

In your code, what is isLocalFileLastModifiedWasDifferent(), isCurrentListWasDifferent()...? Program uses local list index of previous sync ?
Best regards

**Comment by PhilZ-cwm6** [comment]
see issues and comments here:
https://github.com/Sentaroh/SMBSync2/pull/7/commits/b7fea3418c9f62f142fff2a5c2f63ccec58b75fc

and the commit / comments on :
https://github.com/Sentaroh/SMBSync2/pull/8/commits/87404c03000af7b866b6bf0337f52a596e33c616

**Pull request closed without merging**
