### PR TITLE
Fix GUI display exceptions for time and DST offsets

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
- disable DST offset menu when "Use time of last update..." is disabled
- enable save (Ok button) when time difference value is changed

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
Your patch didn't properly fix all the GUI issues:
- if you check "Ignore DST box" and uncheck "Use time of last update", the DST offset list can still be scrolled and changed
- the Ok (save) button is still not enabled when you change only the Allowable time offset list (1, 3, 10)

Here's a proper patch, tested
Thank you a lot

**Comment by PhilZ-cwm6** [comment]
this is ok to merge

**Comment by Sentaroh** [comment]
Sorry, I overlooked your point.

**Comment by PhilZ-cwm6** [comment]
still not fixed, you missed two lines of the code
but I will commit a better fix to effectively hide the list spinner
look next commit

**Pull request closed without merging**
