### PR TITLE
Patch 2020.08.19

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
- do not waste time calling File I/O operations twice
- properly display skipped folders even on non debug + increment skipped/ignored count
- translations
- toast display translation fixes
- add long press toast info for sync button
- revert the new background of sync button
- fix top sync button was not shown in "Select" view if all tasks are set to Manual
- implement comprehensive toast info of the Top Sync button for both Auto and Select modes

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
- fix useless non recommended calling twice for File canRead
- the background of sync icon was really ugly and looking like a bug in teh interface, mainly in dark/light themes

**Comment by PhilZ-cwm6** [comment]
last commits:
I noticed that the top sync button behavior is broken / incomplete:
1- simple translation: onClick, toast message translation in en/fr was not meaning it is synchronizing

2- When no sync tasks is configured on Auto, and we are in Select Sync Tasks mode (check boxes), the top sync button was still disabled: fix it and enable the top menu sync button if at least one valid Sync Task is selected

3- Proper toast info of the top sync button: 
- when Auto tasks are present: toast info that it Auto Sync tasks
- when sync tasks are selected (check box): toast info that it syncs selected tasks

Note 1: I never figured that the to sync button has different actions depending on the view. The toast info is useful

Note 2: I could not get the toast properly update if implemented in onPrepareOptionsMenu(), so implemented it as it should be normally, in onCreateOptionsMenu(). The only part not working with onPrepareOptionsMenu() variant is the toast info on first app start: it defaults to the old "Sync" from view title because View == null on start. Did not spend time on it as the proper way is in the onCreate(), but I put the code commented in onPrepareOptionsMenu() if you need it

Best regards

**Comment by Sentaroh** [comment]
Thank you.

"Revert the non-matching background for the sync button" was not merged to make it clear that it is a button.

Best regards.

**Comment by Sentaroh** [comment]
If you long press the SYNC and SCHEDULE buttons on the schedule tab after applying "Proper toast message info in top sync button", you will see the same message in both cases.

Solved:
image


image
image


Best regards.

**Comment by PhilZ-cwm6** [comment]
I missed that part, thank you for the proper fix and merge
About the icon background: I got it now

Best regards

**Pull request closed without merging**
