### PR TITLE
Patch filters v2 new

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
Major changes:
- add the new custom whole dir prefix `\`
- disable `*` only path components in filters
- improve filters validity checks with many bug fixes
- various bug fixes in filters
- fix crashes in ja/ru (message formatter)
- fix potential NPE error in debug code during sync
- reduce debug overhead during sync

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
Sorry for the many commits. I did not have time to clean and provide less but more structured history. They show the main changes at first, before i fixed and cleaned in the last ones

**Comment by PhilZ-cwm6** [comment]
Added a small fix for Add dir button checks

**Comment by PhilZ-cwm6** [comment]
please see issue track for details

**Comment by PhilZ-cwm6** [comment]
added a check in file filters with path (undocumented support for file filters with path) to not allow asterisk in path, except in the file name

**Comment by PhilZ-cwm6** [comment]
Hopefully my last enhancement in filters
The previous way invalid_chars[] was implemented was not good because editFilter() cannot know the type of filter we're editing
Now, editFilter() is passed the filter type directly and we can properly make specific checks on file and dir filters when Ok button is pressed and before adding the invalid filters

In SMBSync3, this can also be used to add more checks when editing existing wifi filters

Hope you can merge this long pull request

I am holding any further commits until all this is validated by you

Best regards

**Comment by PhilZ-cwm6** [comment]
Hopefully my last enhancement in filters
The previous way invalid_chars[] was implemented was not good because editFilter() cannot know the type of filter we're editing
Now, editFilter() is passed the filter type directly and we can properly make specific checks on file and dir filters when Ok button is pressed and before adding the invalid filters

In SMBSync3, this can also be used to add more checks when editing existing wifi filters

Hope you can merge this long pull request. I am holding any further commits until all this is merged

Best regards

Edit: review of yesterday changes and small cleanup

**Comment by Sentaroh** [comment]
Your changes have been merged.

Best regards.

**Pull request closed without merging**
