### PR TITLE
compression level list: show proper title

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
+ remove unused code
+ code cleanup for readability

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
Zip level compression menu was displaying the wrong title, noticed during translation
removed some unused code also

Edit: I am done with english corrections and french translation for the msg_ strings
I found the way to export in your excel 👍 
There are some parts in the code that need clarification I think, will push the translation in next days
Once ok, for you, I will look at the html help pages to also fix english and add french

**Comment by Sentaroh** [comment]
Thank you.
Your changes have been merged.

**Comment by Sentaroh** [comment]
The HTML of Help is written in MS Word.
Please refer to the file that was uploaded.(help/SMBSync2_.....docx)

**Comment by PhilZ-cwm6** [comment]
👍

**Pull request closed without merging**
