### PR TITLE
Exclude filter use friendly syntax

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
Check details in issue comments please

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
code cleaned up and faster, see issue track

**Comment by PhilZ-cwm6** [comment]
see issue track for details + todo

**Comment by Sentaroh** [comment]
Thank you.

isDirectoryToBeProcessedVer1() and isDirectorySelectedByDirectoryNameVer1() will not be changed because of the high impact on existing users.

The changes are in IsDirectoryToBeProcessedVer2() and isDirecto rySelectedByDirectoryNameVer2(), please.

Best regards.

**Comment by PhilZ-cwm6** [comment]
I understand, sure
Please note that the changes in above code do not modify at all existing filters. At worst, non working filter will be working.
I can modify ver2 to match proposed ver1 changes if ok?

**Comment by Sentaroh** [comment]
Thank you.
> I can modify ver2 to match proposed ver1 changes if ok?

OK.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Complete fix lost Messages bug: This was driving me nuts!
After your commit, I got the saveMsgList() function and added also here:
- onResume() is entered after sync task
- onPause/onStop when in Settings and app in background

After compile and start in emulator, Messages of previous sync are lost. Simulates an unexpected app/device crash

These fix the messages lost after force restart

**Comment by PhilZ-cwm6** [comment]
I am modifying the filter v2
Best regards

**Comment by Sentaroh** [comment]
To deal with message loss on Task clear or Process kill, the Change the saveMsgList() in the following two places.
-SyncThread synchronization end.
-Activity's onPause()

Best regards.

**Pull request closed without merging**
