### PR TITLE
Move color code, translations, import old messages

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
- Properly display Messages from previous version
Support displaying messages of previous versions
After update to new Messages layout , we can no longer read the previous Messages log because they are 4 elements vs 7 in the new layout
Ensure no NPE if message is smaller than the 7 new elements

- Small translations
  + en/fr small spelling fix
  + Excel template: move the new skipped/failed messages to appropriate section
  + merge the japaneese xml changes into Excel template

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
Also moved colors to Utilities global Theme config

This can be merged, but will need a new fix to display Messages entries before migrating to this version. They now appear in a single line with trailing...
It was working with my original commit, but now, text doesn't wrap. Didn't look at it but probably in the layout ?

**Comment by PhilZ-cwm6** [comment]
Sorry, messed up with my repo
On first time SMBSync2 will be updated to the new 2.30, user can no longer read previous Messages in app TAB

My first patch is no more valid because Title was moved to the horizontal one line layout with time/date

Old version log is 4 entries, [4] is Msg. New is 7 entries, [4] is Title, [5] is Msg

Option 1: mention in update that Messages are no longer displayed but accessed in History log
Option 2: merge something like my commit

Note: won't work if messages file was broken with my previous patch. 

To test:
- install v2.29, have a ".messages" file from 2.29
- update to 2.30 with my patch
- old Messages are displayed properly

Only cosmetic..., so drop it if you want

**Comment by Sentaroh** [comment]
Thank you.

The \".messages\" file should be initialized.

Message display has been changed.
図1
図2
図3

Best regards.

**Comment by PhilZ-cwm6** [comment]
Yes, better like this than hack around Title -> Message
Best regards

**Pull request closed without merging**
