### PR TITLE
properly initialize spinner

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
Fixes app crash when parsing a settings file with improper field

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
I verified and quiet all above spinners initialisation needs proper else termination for exception handling of an incorrect setting passed to app

**Review by PhilZ-cwm6 — COMMENTED** [review]
typo fix cv = 1 and not cv == 1

**Comment by Sentaroh** [comment]
Hi,

The code has been modified.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Reading settings file is the most common vulnerability: either user error, intentional or corruption of settings file:
- parser/reader: must take into account that input is an array instead of number, that array size is bigger than expected (segmentation fault, out of memory, leak...)
- init values: always init the values that user could delete or modify and verify array, integer, limits allowed and size properties

In your code, there is little or no check on parser entries. I would fix them

The error i got crashed the app and corrupted installation. To update, i had to uninstall apk first. So a simple error in settings file corrupted all the app installation ! 

Again, I love your app for the smb3 support. I am happy to help if i can and have time

Best regards

**Pull request closed without merging**
