### PR TITLE
Patch fix mirror deletes + Add Exact Target Mirror Image Option

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
**1. Fix Unexpected File deletes on the target:**
The use of isDirectoryToBeProcessed() is not appropriate for checking files against filters

exp:
- create file filter to exclude `*.jpg` files
- on target, create a file.jpg
- after mirror sync, it is deleted
This behavior is non consistent with the directory sync approach preserving target from deletes outside the filtered elements

**2. Fix Unexpected dir deletes in Mirror Internal/External to External:**
**This affects only Mirror mode from External/Internal to External storage**
If you delete existing directory on master, it was deleted from target even if it was excluded from Sync by directory filters.
However, if you **Only** exclude it from sync without deleting from Master, it was not deleted on target

Patches 1) + 2) are serious bug fixes. They make the sync behavior consistent and stop inconsistently deleting target files and folders if they are excluded from sync

**3. Add option to make Target an exact image of Source directory in Mirror mode**

- **Option disabled:** original behavior fixed with 1) and 2): no target files/dirs are ever deleted if they are not included by the filters. Only the included files/dirs that are deleted from the Source will be deleted from the Target
- **Option enabled:** Target is ensured to be an exact image copy of the Source. Any files/dirs that are not matching the include/exclude filters will be deleted from the Target. Any included files/dirs will still be removed from target if they no longer exist on Source

**4. Notify GUI that the Mirror exact image mode is enabled**
check images below

**5. Fix unexpected deletes in ZIP MIrror mode***
- respect filters and hidden files/dirs options
- support the exact image mode

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
**Same exact as previous + rebase + see last commit fixing a bug in my previous commit**

It is the same as the commit you merged and reverted (bug fix of non expected deletes) + the more readable code to show when we delete and when we recurse + the new create exact mirror image option

The only code changes with base version are adding this
```
// for dirs
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete the target dir if source dir doesn't exist OR if it is excluded by dir filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir);
                process_subdirs = !remove_tf;
            } else if (SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir)) {//delete target dir if it is included by dir filter AND it is deleted from source dir
                mf = new File(master_dir);
                remove_tf = !mf.exists();
                process_subdirs = !remove_tf;
            } //target dir is excluded by filters: never remove target dir (remove_tf=false), mf.exists(): do not wate time checking it, process_subdirs=false (do not further recurse)


// for files
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete target file if source doesn't exist or if the file is excluded/not included by filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) || !SyncThread.isFileSelected(stwa, sti, tmp_target_dir);
            } else if (SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) && SyncThread.isFileSelected(stwa, sti, tmp_target_dir)) {//delete target file if it is included by filters and it doesn't exist on source
                mf = new File(master_dir);
                remove_tf = !mf.exists();
            } //file is excluded by filters: never remove target file, mf.exists(): do not wate time checking it
```

Then, only the delete code is moved before the recurse subdirs for an if/else simpler code

So, the delete/recurse code was not changed, just the if/else check rules

Beyond Compare tool gives a better idea on the changes than git:
diff


Best regards

**Comment by PhilZ-cwm6** [comment]
**Same exact as previous + rebase + see last commit fixing a bug in my previous commit**

It is the same as the commit you merged and reverted (bug fix of non expected deletes) + the more readable code to show when we delete and when we recurse + the new create exact mirror image option

The only code changes with base version are adding this
```
// for dirs
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete the target dir if source dir doesn't exist OR if it is excluded by dir filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir);
                process_subdirs = !remove_tf;
            } else if (SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir)) {//delete target dir if it is included by dir filter AND it is deleted from source dir
                mf = new File(master_dir);
                remove_tf = !mf.exists();
                process_subdirs = !remove_tf;
            } //target dir is excluded by filters: never remove target dir (remove_tf=false), mf.exists(): do not wate time checking it, process_subdirs=false (do not further recurse)


// for files
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete target file if source doesn't exist or if the file is excluded/not included by filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) || !SyncThread.isFileSelected(stwa, sti, tmp_target_dir);
            } else if (SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) && SyncThread.isFileSelected(stwa, sti, tmp_target_dir)) {//delete target file if it is included by filters and it doesn't exist on source
                mf = new File(master_dir);
                remove_tf = !mf.exists();
            } //file is excluded by filters: never remove target file, mf.exists(): do not wate time checking it
```

Then, only the delete code is moved before the recurse subdirs for an if/else simpler code

So, the delete/recurse code was not changed, just the if/else check rules

Beyond Compare tool gives a better idea on the changes than git:
diff


Best regards

**Comment by PhilZ-cwm6** [comment]
Last commit:
Screenshot_1594590207
Screenshot_1594590214

I thought it is good to notify user of this option being enabled
Another option is to Add a new sync type in the spinner: Image. When it is selected, it only sets the SyncOptionEnsureTargetIsExactMirror option instead of a check mark and keeps the sync mode internally as Mirror

In any-case, a true image mode like I submitted is really needed to trash the excluded files/dirs when needed

I let you keep it as I propose (visual hack) or if you prefer you change it to a new Sync Mode.
Should be simple as the sync code won't change

Many thanks and best regards

**Comment by PhilZ-cwm6** [comment]
**1. Same exact as previous + rebase + see last commit fixing a bug in my previous commit**

It is the same as the commit you merged and reverted (bug fix of non expected deletes) + the more readable code to show when we delete and when we recurse + the new create exact mirror image option

The only code changes with base version are adding this
```
// for dirs
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete the target dir if source dir doesn't exist OR if it is excluded by dir filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir);
                process_subdirs = !remove_tf;
            } else if (SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir)) {//delete target dir if it is included by dir filter AND it is deleted from source dir
                mf = new File(master_dir);
                remove_tf = !mf.exists();
                process_subdirs = !remove_tf;
            } //target dir is excluded by filters: never remove target dir (remove_tf=false), mf.exists(): do not wate time checking it, process_subdirs=false (do not further recurse)


// for files
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete target file if source doesn't exist or if the file is excluded/not included by filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) || !SyncThread.isFileSelected(stwa, sti, tmp_target_dir);
            } else if (SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) && SyncThread.isFileSelected(stwa, sti, tmp_target_dir)) {//delete target file if it is included by filters and it doesn't exist on source
                mf = new File(master_dir);
                remove_tf = !mf.exists();
            } //file is excluded by filters: never remove target file, mf.exists(): do not wate time checking it
```

Then, only the delete code is moved before the recurse subdirs for an if/else simpler code

So, the delete/recurse code was not changed, just the if/else check rules

Beyond Compare tool gives a better idea on the changes than git:
diff


Best regards


**2. Notify user of the new exact image mode:**

images:
Screenshot_1594590207
Screenshot_1594590214

I thought it is good to notify user of this option being enabled
Another option is to Add a new sync type in the spinner: Image. When it is selected, it only sets the SyncOptionEnsureTargetIsExactMirror option instead of a check mark and keeps the sync mode internally as Mirror

In any-case, a true image mode like I submitted is really needed to trash the excluded files/dirs from target (case temp/cache/thumb files for example)

I let you keep it as I propose (visual hack) or if you prefer you change it to a new Sync Mode.
Should be simple as the sync code won't change


**3. Fix ZIP non expected deletes:**

syncDeleteInternalToInternalZip() method was always purging the ZIP like the exact image mode, except it never checks the filters. So it is a bit inconsistent: if master file doesn't exist, it is deleted from target, either it is included or excluded by the filters. However, when it is excluded but it exists on the master, it will not be purged from the ZIP !
Also, it did not respect the hidden files/dir option

The patch properly fixes the ZIP mirror mode and removes all non expected deletes: respect filters and hidden files/dirs option

**Comment by PhilZ-cwm6** [comment]
**1. Same exact as previous + rebase + see last commit fixing a bug in my previous commit**

It is the same as the commit you merged and reverted (bug fix of non expected deletes) + the more readable code to show when we delete and when we recurse + the new create exact mirror image option

The only code changes with base version are adding this
```
// for dirs
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete the target dir if source dir doesn't exist OR if it is excluded by dir filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir);
                process_subdirs = !remove_tf;
            } else if (SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir)) {//delete target dir if it is included by dir filter AND it is deleted from source dir
                mf = new File(master_dir);
                remove_tf = !mf.exists();
                process_subdirs = !remove_tf;
            } //target dir is excluded by filters: never remove target dir (remove_tf=false), mf.exists(): do not wate time checking it, process_subdirs=false (do not further recurse)


// for files
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete target file if source doesn't exist or if the file is excluded/not included by filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) || !SyncThread.isFileSelected(stwa, sti, tmp_target_dir);
            } else if (SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) && SyncThread.isFileSelected(stwa, sti, tmp_target_dir)) {//delete target file if it is included by filters and it doesn't exist on source
                mf = new File(master_dir);
                remove_tf = !mf.exists();
            } //file is excluded by filters: never remove target file, mf.exists(): do not wate time checking it
```

Then, only the delete code is moved before the recurse subdirs for an if/else simpler code

So, the delete/recurse code was not changed, just the if/else check rules

Beyond Compare tool gives a better idea on the changes than git:
diff


Best regards


**2. Notify user of the new exact image mode:**

images:
Screenshot_1594590207
Screenshot_1594590214

I thought it is good to notify user of this option being enabled
Another option is to Add a new sync type in the spinner: Image. When it is selected, it only sets the SyncOptionEnsureTargetIsExactMirror option instead of a check mark and keeps the sync mode internally as Mirror

In any-case, a true image mode like I submitted is really needed to trash the excluded files/dirs from target (case temp/cache/thumb files for example)

I let you keep it as I propose (visual hack) or if you prefer you change it to a new Sync Mode.
Should be simple as the sync code won't change


**3. Fix ZIP non expected deletes:**

syncDeleteInternalToInternalZip() method was always purging the ZIP like the exact image mode, except it never checks the filters. So it is a bit inconsistent: if master file doesn't exist, it is deleted from target, either it is included or excluded by the filters. However, when it is excluded but it exists on the master, it will not be purged from the ZIP !
Also, it did not respect the hidden files/dir option

The patch properly fixes the ZIP mirror mode and removes all non expected deletes: respect filters and hidden files/dirs option

**Comment by Sentaroh** [comment]
Merged your changes.
However, I didn't show \"2. Notify user of the new exact image mode:\" because I thought it would confuse users.

The following is a dangerous warning message.
image


Best regards.

**Comment by PhilZ-cwm6** [comment]
Thank you for the merge !
I will open an issue discussion about it
Best regards

**Pull request closed without merging**
