### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
- elapsed time no more in seconds
- remove useless code lefovers

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
just a few code changes missed in your previous commit
In next weeks, I will try to find some time for some translation corrections

**Comment by Sentaroh** [comment]
Thank you for your suggestion and modification.

Merged your updates.

Since Excel is used for String management (message_translation.xlsm), it would be easier for you to prosper if you change the color of the updated text to red.

image

Best regards.

**Comment by Sentaroh** [comment]
Please refer to Branch 2.26 from now on as Ver. 2.25 has been released.

Best regards.

**Comment by PhilZ-cwm6** [comment]
I will in next weeks i hope, yes, it is easier in the excel
Thank you and i will report if needed

**Pull request closed without merging**
