### PR TITLE
Add support for compare by Size only and DST in ZIP and SMB, improvements

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
List of fixes:

- ~~Fix serious bug in Size Only compare~~
  + ~~when "Overwrite only if source file is greater in size than target" was selected, the smaller file was overwritten !~~
- **Better redability of pointed storage in code: target vs master file**
  + **it is only a rename of the variables inside teh functions, no code is altered**
- Support DST offset check when target is ZIP
- Support "Size only compare" when target is SMB
- Support "Size only compare" when target is ZIP
- If both compare by time and compare by size options are disabled, always overwrite destination and add a dialog warning
  + Previously, nothing was copied except new files, this is redundunt to "do not overwrite option"
Also, in other retail Sync programs, when no compare option is selected, files are considered different
This is desirable as we can have a Mirror mode that always copies all files to target overwriting any existing file
- Warning about unexpected results about DST/TimeZone changes risks if "Do not overwrite destination file if it is newer than source file" is checked
  + When a file is changed in the interval of the timezone or DST change, it can appear older than the source.
See details here: https://www.codeproject.com/Articles/1144/Beating-the-Daylight-Savings-Time-bug-and-getting
Workarounds by other app: https://www.scootersoftware.com/support.php?zz=kb_dst
There is no workaround for DST except warning user or avoid modifying target files during the DST change interval
- Hide ZIP non relevant option
  + if target is ZIP, hide the option "Do not set last modified time of destination..."
- Small spelling fixes:
  + fr: missing parenthesis and lowercase in msgs_profile_sync_task_sync_option_diff_file_size_greater_than_target
  + fr-en: small spelling fixes in msgs_profile_sync_task_sync_option_master_root_dir_file

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
You can look at the separate patches
I fully tested with Zip and other modes to ensure the patch is proper
translations excel file included in last patch

**Comment by PhilZ-cwm6** [comment]
I have a doubt on this one:
if (lf_length>tf_length) in SyncThread.java

Your comments mention Target and Master are inversed by caller ?
Not sure at all
But remaining of code should be fine

**Comment by PhilZ-cwm6** [comment]
- Well, it was really upside down in the code !!
I posted a correction that just edits the variables names, no change in code

**Comment by PhilZ-cwm6** [comment]
I added the changes
- Better redability of pointed storage in code: target vs master file
  + it is only a rename of the variables inside teh functions, no code is altered

Proper code, hope you can merge it for a simpler followup

- Zip archiving: works perfectly by file size with my patch
- SMB archiving: copy by size also works as expected with the patch

Note: Issue, present already with your stock versions: Zip cannot compress files located on External SD, didn't look at it yet

**Comment by Sentaroh** [comment]
>Zip cannot compress files located on External SD
I forgot to check the folder type.

Best regards.

**Comment by PhilZ-cwm6** [comment]
👍 
thank you

**Pull request closed without merging**
