### PR TITLE
Translations and exceptions handling

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
- Translation of sync modified files since today
- Handling of exceptions if code is modified in the future

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
Hi,

I amended my previous pull request
I kept the handling of exceptions that could lead to issues in the future if code is modified
Best regards

**Comment by Sentaroh** [comment]
Hi,

I think "TODAY" is fine for most of the synchronizations, but if the synchronization starts at 23:59 and ends at 00:05, after 00:00 it will be "YESTERDAY" instead of "TODAY", so I don't agree with changing FILTER_FILE_DATE_TYPE_. SYNC_BEGIN_DAY to FILTER_FILE_DATE_TYPE_TODAY.
The current code has a bug and will be fixed.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Hi,
No, I did not change it today, but "Since Today", that is from the current day at 00:00:00 till next day at 23:59:00
I also thought at it and changed my mind to not use "today"

So the labelling "Since today" is fine in the english, french and italian translations I changed (Russian is gogle, and I don't understand Russian)

I will look at your next changes
Best regards

**Comment by Sentaroh** [comment]
Hi,

Changed to cover the period from 00:00:00.000 to 23:59:59.999 of the synchronization start date.
https://github.com/Sentaroh/SMBSync2/commit/8b8f35502526a212a1f7e9e2a77c255b48438a42

Best regards.

**Comment by Sentaroh** [comment]
Hi,

I will fix it, please wait until we update it.

Best regards.

**Comment by Sentaroh** [comment]
Hi,

SYNC_BEGIN_DATE in the File date filter now targets the start date of synchronization after 00:00:00.000.
https://github.com/Sentaroh/SMBSync2/commit/5b18a618cb820501b9b072e8506613cfa900ba4d

Best regards.

**Pull request closed without merging**
