### PR TITLE
Partial fix to ShowDialog() big text: see comment

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
This is a partial fix
- ShowDialog() is still not scrollable but it fills better the screen with the text
Buttons in the "<include layout="@layout/show_warning_message_dlg_ok_cancel" />" cannot be set in the scrollable layout
- Alternative: I shorten the french text
- reproduce: when enable "only overwrite target if it is newer than the master..."

**Before:**
Screenshot_1589131003

**How it should be (shorter text in english):**
Screenshot_1589142208

**Comment by Sentaroh** [comment]
Utilities/common_dialog.xml has been fixed.
pic1

**Comment by PhilZ-cwm6** [comment]
I didn't figure it was in Utilities, thanks

Can you look at this layout issue: on my two main devices, Galaxy S7 and Note 4, when in portrait orientation, it shows settings menu in the Large layout (split screen) instead of normal which would be more adapted. Menus are all truncated with the three dots...

Note 4 is 480dp, so I guess Large applies, but why on the S7 which is 360dp ?
Also, I think large should not split settings screen, but rather start splitting at an xlarge layout or only in landscape ((+600dp)

**Galaxy Note 4: 1440 x 2560 (518 dpi) --> 480dp width:**
Screenshot_Galaxy_Note4_1440px518dpi


**Galaxy S7 1440 x 2560 (577 dpi) --> 360dp width:** better because english is shorter
Screenshot_Galaxy_S7_1440px577dpi


**Note**: can you enable "issues" on your SMBSync2 repo ? Simpler to submit issues than having to pull a request or comment in code
Capture

**Comment by Sentaroh** [comment]
>Note 4 is 480dp, so I guess Large applies, but why on the S7 which is 360dp ?
You can use one of the following to display a split screen. (ActivitySettings#onIsMultiPane())
1.min(screen height, width)>=1200Pixel
2.The screen is facing sideways.

As a workaround, I made it over 1600 pixels.

**Comment by Sentaroh** [comment]
Enable ”Issue” feature.

**Comment by PhilZ-cwm6** [comment]
I saw your patch
isn't it better to use screen width in dp in your patch ? Because at 1600, screen can still be low in dp. 
https://stackoverflow.com/questions/6465680/how-to-determine-the-screen-width-in-terms-of-dp-or-dip-at-runtime-in-android

Large would start a 600dp (instead of recommended 480dp because SMBSync2 needs space for menus). Also, many small screens have a high dp
https://developer.android.com/training/multiscreen/screensizes
https://material.io/resources/devices/

```
getDisplayMetrics().densityDpi;
int width_dp = (width_px/pixeldpi)*160;
int height_dp = (height_px/pixeldpi)*160;
```

**Comment by PhilZ-cwm6** [comment]
see my commit please to use dp

**Pull request closed without merging**
