### PR TITLE
Update help doc for filters v2

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
Help file was using the `*` char to match any directory, which is now deprecated
The doc I edited describes filters v2, so filters v1 is not covered

I let you decide if you add something about it like "It is recommended to migrate to filters v2. The below examples apply only to filters v2" or you want to add notes on filters v1, knowing that it is broken in some parts

Best regards

**Comment by Sentaroh** [comment]
Thank you.

>Filter V2

I don't think it's necessary to describe it in detail in the help because the guide will be shown on the filter editing screen.

- File filter
  You can select the name and extension of the file you want to synchronize with other than the above.

- Select sub directories for sync
   If you do not check and then sync all of the sub directory. If you check to show directory filter button.
   - Directory filter
   You can select the name of the directory you want to synchronize.


>trailing / .......

I understood \"/dir/\", \"/dir\" and \"dir/\" to mean the same thing in the directory filter, but they're not?

Best regards.

**Comment by PhilZ-cwm6** [comment]
- Filter `dir` : match `master/dir` include `dir`
- Filter `dir/` matches `master/dir/subdirs`, `master/dir/files`, but not `master/dir` - > create (or keep existing) **EMPTY** excluded `dir` on target. Very useful personally to see on target the non sync/exluded folders location (exp `apps/cache/`) 

In include filter, result is same obviously

It is like cp/mv all files and subdirs `dir/*` vs mv/cp `dir` AND all its files/subdirs in on some versions of linux/bsd or rsync... 

Have a good summer and best regards

**Comment by Sentaroh** [comment]
Thank you.

You may answer after your vacation is over.

Creating subdirectories in an Excluded directory is against the Exclude, so I don't want to create a subdirectory in an Excluded directory.

Best regards.

**Comment by PhilZ-cwm6** [comment]
I don't understand
filter `dir` will not create the empty excluded dir. Only if filter is `dir/`
That is it must be a directory filter + ends with `/`

I really need that feature in my synchronized SMB target for excluded folders like `Music/`, `DCIM/Camera/Saved/` to manage second task backups of the NAS

By the way, in filters v1, the empty directories were always created when excluded. So the new v2 I added kept that feature + fixed it to respect the trailing `/` rule

Hope you don't remove it as it doesn't cost any overhead + it respects the linux mv/cp rules on many BSD versions, include iOS as I read. I also need it for second tasks backups of the NAS. Maybe do not document it if you like... People won't complain as it was already the case with v1

Best regards

**Note**: I will wait to publish on xda/phoneDroid until filters v2 is enabled in a release. Filters v1 is broken in many parts and I don't feel advertising the app with it (non expected data deletes on target + filter not applying). The post text is written since a few weeks, so I will just copy/paste it once it is activated. I would recommend strongly new adopters to activate filter v2 on first use and to not use v1

**Pull request closed without merging**
