### PR TITLE
Patch fix mirror deletes + Add Exact Target Mirror Image Option

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
**1. Fix Unexpected File deletes on the target:**
The use of isDirectoryToBeProcessed() is not appropriate for checking files against filters

exp:
- create file filter to exclude `*.jpg` files
- on target, create a file.jpg
- after mirror sync, it is deleted
This behavior is non consistent with the directory sync approach preserving target from deletes outside the filtered elements

**2. Fix Unexpected dir deletes in Mirror Internal/External to External:**
**This affects only Mirror mode from External/Internal to External storage**
If you delete existing directory on master, it was deleted from target even if it was excluded from Sync by directory filters.
However, if you **Only** exclude it from sync without deleting from Master, it was not deleted on target

Patches 1) + 2) are serious bug fixes. They make the sync behavior consistent and stop inconsistently deleting target files and folders if they are excluded from sync

**3. Add option to make Target an exact image of Source directory in Mirror mode**

- **Option disabled:** original behavior fixed with 1) and 2): no target files/dirs are ever deleted if they are not included by the filters. Only the included files/dirs that are deleted from the Source will be deleted from the Target
- **Option enabled:** Target is ensured to be an exact image copy of the Source. Any files/dirs that are not matching the include/exclude filters will be deleted from the Target. Any included files/dirs will still be removed from target if they no longer exist on Source

### CODE REVIEW

**Comment by Sentaroh** [comment]
Thank you.

Please wait a couple of days as we test it.

Best regards.

**Comment by PhilZ-cwm6** [comment]
I did not notice your merge before I commit. I wanted to rebase it on latest branch.
It is the same of the commit you merged and reverted (bug fix of non expected deletes) + the more readable code to know when we delete and when we recurse + the exact image mirror option

The only code changes for each method are adding this
```
// for dirs
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete the target dir if source dir doesn't exist OR if it is excluded by dir filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir);
                process_subdirs = !remove_tf;
            } else if (SyncThread.isDirectoryToBeProcessed(stwa, tmp_target_dir)) {//delete target dir if it is included by dir filter AND it is deleted from source dir
                mf = new File(master_dir);
                remove_tf = !mf.exists();
                process_subdirs = !remove_tf;
            } //target dir is excluded by filters: never remove target dir (remove_tf=false), mf.exists(): do not wate time checking it, process_subdirs=false (do not further recurse)


// for files
            if (sti.isSyncOptionEnsureTargetIsExactMirror()) {//delete target file if source doesn't exist or if the file is excluded/not included by filters
                mf = new File(master_dir);
                remove_tf = !mf.exists() || !SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) || !SyncThread.isFileSelected(stwa, sti, tmp_target_dir);
            } else if (SyncThread.isDirectorySelectedByFileName(stwa, tmp_target_dir) && SyncThread.isFileSelected(stwa, sti, tmp_target_dir)) {//delete target file if it is included by filters and it doesn't exist on source
                mf = new File(master_dir);
                remove_tf = !mf.exists();
            } //file is excluded by filters: never remove target file, mf.exists(): do not wate time checking it
```

Then, only the delete code is moved before the recurse subdirs for an if/else simpler code

So, the delete/recurse code was not changed, just the if/else check rules

Beyond Compare tool gives a better idea on the changes than git:
diff



Best regards

**Comment by PhilZ-cwm6** [comment]
updated the excel file with your latest changes

**Comment by PhilZ-cwm6** [comment]
need a small fix, will commit in a moment, sorry

**Pull request closed without merging**
