### PR TITLE
Patch scroll long path in main view + Long click on sync icon

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
- properly support scroll of long path names in master/target fields
- support long click on the task sync icon to select items

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
This looks proper to me
I arranged the methods in Main Activity to reuse the same code instead of dup code
I also added support to long click on the sync icon to select the task items (enable check box view) which was not supported

Best regards

**Comment by Sentaroh** [comment]
Thank you for your efforts.

I don't want to do a complicated process for scrolling, so how about showing everything as shown below?

image

image

If you agree with me, I'll fix it for you.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Yes, I really agree for the image 1, the one on the main activity view with the list of tasks. That way we see the full path of smb shares. It also doesn't pose problem aesthetically.

The second one, EditSyncTask dialog: functionally your pic is good. However, the ScrollView implementation you already merged is a better functional/aesthetics compromise. It is ok for me if you change like in picture, but I prefer the current HorizontalScrollView. So do what you think is better.

By the way, I was about to fix the broken highlight on click of my code using MotionEvent.obtain() on the dispatched EditText click. So I am dropping it and waiting for your fix.

Thank you and best regards

**Comment by Sentaroh** [comment]
Please check "2.32-long-path" branch.

image

image

Best regards.

**Comment by PhilZ-cwm6** [comment]
I close this and comment on the other pull request, 
best regards

**Pull request closed without merging**
