### PR TITLE
Proper fix for ZIP restrictions on master/target folders

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
- properly fix ZIP set as target while source is not on Internal Storage
- fr/eng translation fixes of last commit
- remove extra CRLF in excel/xml template

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
- check was not applied when changing target folder to ZIP while Master was not on Internal
- on target: always revert to previous choice to avoid undesirable effects if user doesn't take care that his target path was changed: possibility to erase all data
- change the logic: only revert the change user is doing and do not alter the target if master is edited (and vice-versa). Keeps with the UI design that saves previous settings on pages changes + avoids unexpected results if user doesn't take care
- folder_type was not compared to good type

**Comment by PhilZ-cwm6** [comment]
I have a question please:
Does the NonWordwrapTextView class support NonWordwrapTextView or simpler TextView linear consecutive positions ?

Desired view:

```
[NON wrappable text entry] [wrappable text entry]
```
eventually if mixing NonWordwrapTextView  and TextView is not possible:
```
[NON wrappable text entry] [NON  wrappable text entry]
```

instead of the current rendered layout:
```
[NON wrappable text entry]
[Wrappable text entry]
```

these don't work
```
<LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal">
    <com.sentaroh.android.SMBSync2.NonWordwrapTextView
        android:id="@+id/msg_list_view_item_msg"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="15dp"
        android:layout_marginRight="5dp"
        android:text="Small Text"
        android:textAppearance="?android:attr/textAppearanceSmall"/>

    <com.sentaroh.android.SMBSync2.NonWordwrapTextView
        android:id="@+id/msg_list_view_item_type"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginLeft="15dp"
        android:text=""
        android:textAppearance="?android:attr/textAppearanceSmall"/>
</LinearLayout>
```
This doesn't work, neither removing the LinearLayout

Also this one to continue a non word wrap TexView after the NonWordwrapTextView doesn't work

```
<LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal">
    <com.sentaroh.android.SMBSync2.NonWordwrapTextView
        android:id="@+id/msg_list_view_item_msg"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="15dp"
        android:layout_marginRight="5dp"
        android:text="Small Text"
        android:textAppearance="?android:attr/textAppearanceSmall"/>

    <TextView
        android:id="@+id/msg_list_view_item_type"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginLeft="15dp"
        android:text=""
        android:textAppearance="?android:attr/textAppearanceSmall"
         />
</LinearLayout>
```

I was working on improving the Messages layout to properly display [File opérations] in color for deletes, but not all the line. It will be easier to spot deleted files/overwrritten files

Else, I end up with and extra line and need to hide it when type is not used (edit: hiding the line on demand works perfectly)

Any idea if it is possible without a new line entry after the NonWordwrapTextView entry ?

**Comment by PhilZ-cwm6** [comment]
swap folders button must be restored on target revert

**Comment by Sentaroh** [comment]
1.Your changes was merged.

2.[NON wrappable text entry] [wrappable text entry]
You can dynamically switch to WordWrap by using NonWordWrapTextView#setWordWrapEnabled(true).

3.Color change
Spannanble can be used to color a portion of a string.
The code can be found at https://github.com/Sentaroh/WordWrapTest/blob/master/app/src/main/java/com/sentaroh/android/wordwraptest/MainActivity.kt.
pic1

**Comment by PhilZ-cwm6** [comment]
thank you

**Pull request closed without merging**
